Repository jinan159/todo-list, pull requests merged in 2022-04, with the labels that each got.

#9 [iOS] 앱 전체 레이아웃 구성
  ios/TodoApp/TodoApp.xcodeproj/project.pbxproj
  ios/TodoApp/TodoApp/Controllers/ActivityTableViewController.swift
  ios/TodoApp/TodoApp/Controllers/TodoListContainerViewController.swift
  ios/TodoApp/TodoApp/Controllers/TodoListViewController.swift
  ios/TodoApp/TodoApp/Resources/Assets.xcassets/Background.colorset/Contents.json
  ios/TodoApp/TodoApp/Supporting Files/Base.lproj/Main.storyboard
Labels: 👀 View

#11 [공통] 풀리퀘스트 템플릿 추가
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#14 [BE] feat: 칼럼 조회 기능 추가
  be/src/main/java/com/ijava/todolist/column/controller/ColumnController.java
  be/src/main/java/com/ijava/todolist/column/controller/dto/ColumnResponse.java
  be/src/main/java/com/ijava/todolist/column/domain/Column.java
  be/src/main/java/com/ijava/todolist/column/repository/ColumnRepository.java
  be/src/main/java/com/ijava/todolist/column/repository/JDBCColumnRepository.java
  be/src/main/java/com/ijava/todolist/column/service/ColumnService.java
  be/src/main/resources/sql/test/column-dml-h2.sql
  be/src/test/java/com/ijava/todolist/column/controller/ColumnControllerTest.java
  be/src/test/java/com/ijava/todolist/column/repository/ColumnRepositoryTest.java
  be/src/test/java/com/ijava/todolist/column/service/ColumnServiceTest.java
Labels: ✨ Feature

#15 [BE] GlobalExceptionHandler 전역 예외반환 형식 개선 반영 요청
  be/src/main/java/com/ijava/todolist/exception/ErrorResponse.java
  be/src/main/java/com/ijava/todolist/exception/GlobalExceptionHandler.java
  be/src/test/java/com/ijava/todolist/exception/GlobalExceptionHandlerTest.java
Labels: ♻️ Refactor

#16 [iOS] ToDoList 컬럼 구현
  ios/TodoApp/TodoApp.xcodeproj/project.pbxproj
  ios/TodoApp/TodoApp/Controllers/TodoListViewController.swift
  ios/TodoApp/TodoApp/Supporting Files/Base.lproj/Main.storyboard
  ios/TodoApp/TodoApp/Views/ToDoCell.swift
Labels: 👀 View

#19 [BE] feat: 활동기록 기능 구현
  be/src/main/java/com/ijava/todolist/history/Action.java
  be/src/main/java/com/ijava/todolist/history/controller/HistoryController.java
  be/src/main/java/com/ijava/todolist/history/controller/dto/HistoryResponse.java
  be/src/main/java/com/ijava/todolist/history/domain/History.java
  be/src/main/java/com/ijava/todolist/history/exception/HistoryNotSavedException.java
  be/src/main/java/com/ijava/todolist/history/exception/HistoryRuntimeException.java
  be/src/main/java/com/ijava/todolist/history/repository/HistoryRepository.java
  be/src/main/java/com/ijava/todolist/history/repository/JdbcHistoryRepository.java
  be/src/main/java/com/ijava/todolist/history/service/HistoryService.java
  be/src/main/java/com/ijava/todolist/history/util/HistoryResolver.java
  be/src/main/java/com/ijava/todolist/user/domain/User.java
  be/src/main/java/com/ijava/todolist/user/exception/UserNotFoundException.java
  be/src/main/java/com/ijava/todolist/user/exception/UserRuntimeException.java
  be/src/main/java/com/ijava/todolist/user/repository/JdbcUserRepository.java
  be/src/main/java/com/ijava/todolist/user/repository/UserRepository.java
  be/src/main/java/com/ijava/todolist/user/service/UserService.java
  be/src/main/resources/sql/ddl-h2.sql
  be/src/main/resources/sql/test/history-dml-h2.sql
  be/src/main/resources/sql/test/user-dml-h2.sql
  be/src/test/java/com/ijava/todolist/history/controller/HistoryControllerTest.java
  be/src/test/java/com/ijava/todolist/history/repository/HistoryRepositoryTest.java
  be/src/test/java/com/ijava/todolist/history/service/HistoryServiceTest.java
  be/src/test/java/com/ijava/todolist/history/util/HistoryResolverTest.java
  be/src/test/java/com/ijava/todolist/user/repository/UserRepositoryTest.java
  be/src/test/java/com/ijava/todolist/user/service/UserServiceTest.java
Labels: ✨ Feature

#25 [iOS] ToDoCreation ViewController 구현
  ios/TodoApp/TodoApp.xcodeproj/project.pbxproj
  ios/TodoApp/TodoApp/Controllers/ToDoCreationViewController.storyboard
  ios/TodoApp/TodoApp/Controllers/ToDoCreationViewController.swift
  ios/TodoApp/TodoApp/Controllers/TodoListViewController.storyboard
  ios/TodoApp/TodoApp/Supporting Files/Base.lproj/Main.storyboard
Labels: 👀 View, ✨ Feature

#26 [iOS] 데이터 모델 추가 및 storyboard 삭제 작업
  ios/TodoApp/TodoApp.xcodeproj/project.pbxproj
  ios/TodoApp/TodoApp/Controllers/Base.lproj/TodoListContainerViewController.storyboard
  ios/TodoApp/TodoApp/Controllers/TodoCreationViewController.storyboard
  ios/TodoApp/TodoApp/Controllers/TodoCreationViewController.swift
  ios/TodoApp/TodoApp/Controllers/TodoListContainerViewController.swift
  ios/TodoApp/TodoApp/Controllers/TodoListViewController.storyboard
  ios/TodoApp/TodoApp/Controllers/TodoListViewController.swift
  ios/TodoApp/TodoApp/Extensions/Logger+Extensions.swift
  ios/TodoApp/TodoApp/Models/Column.swift
  ios/TodoApp/TodoApp/Models/Todo.swift
  ios/TodoApp/TodoApp/SceneDelegate.swift
  ios/TodoApp/TodoApp/Supporting Files/Info.plist
  ios/TodoApp/TodoApp/Views/TodoCell.swift
Labels: ♻️ Refactor, ✨ Feature

#29 [iOS] 활동 기록 & 서버 fetch 작업
  ios/TodoApp/ActivityNetworkTests/ActivityNetworkTests.swift
  ios/TodoApp/TodoApp.xcodeproj/project.pbxproj
  ios/TodoApp/TodoApp/Controllers/ActivityListViewController.swift
  ios/TodoApp/TodoApp/Extensions/NotificationCenter.swift
  ios/TodoApp/TodoApp/Models/Entity/Activity.swift
  ios/TodoApp/TodoApp/Models/NetworkHandler.swift
  ios/TodoApp/TodoApp/Views/ActivityCell.swift
Labels: bug, ✨ Feature

#30 [BE] mysql 연동 및 배포를 위한 프로파일 설정
  be/build.gradle
  be/src/main/resources/application.yml
Labels: 👷Infra

#31 [BE] 배포용 프로필 설정 및 브랜치 추가
  be/src/main/resources/application.yml
  be/src/main/resources/logback-spring.xml
  be/src/main/resources/logback.xml
Labels: 👷Infra

#33 fix: 삭제된 카드는 개수를 세지 않도록 수정
  be/src/main/java/com/ijava/todolist/card/repository/JdbcCardRepository.java
Labels: bug

#35 docs: Swagger 를 통한 API 문서 자동화 적용
  be/build.gradle
  be/src/main/java/com/ijava/todolist/card/controller/CardController.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardCreateRequest.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardDeleteResponse.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardMoveRequest.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardMovedResponse.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardResponse.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardUpdateRequest.java
  be/src/main/java/com/ijava/todolist/column/controller/ColumnController.java
  be/src/main/java/com/ijava/todolist/column/controller/dto/ColumnResponse.java
  be/src/main/java/com/ijava/todolist/config/SwaggerConfig.java
  be/src/main/java/com/ijava/todolist/history/controller/HistoryController.java
  be/src/main/java/com/ijava/todolist/history/controller/dto/HistoryResponse.java
Labels: 📄Documentation, ✨ Feature

#36 docs: Swagger 를 통한 API 문서 자동화 적용 (#35)
  be/build.gradle
  be/src/main/java/com/ijava/todolist/card/controller/CardController.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardCreateRequest.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardDeleteResponse.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardMoveRequest.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardMovedResponse.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardResponse.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardUpdateRequest.java
  be/src/main/java/com/ijava/todolist/column/controller/ColumnController.java
  be/src/main/java/com/ijava/todolist/column/controller/dto/ColumnResponse.java
  be/src/main/java/com/ijava/todolist/config/SwaggerConfig.java
  be/src/main/java/com/ijava/todolist/history/controller/HistoryController.java
  be/src/main/java/com/ijava/todolist/history/controller/dto/HistoryResponse.java
Labels: 📄Documentation, ✨ Feature
